### PR TITLE
[ci] Re-enable L2 Benchmarks

### LINKED ISSUE #926: [ci] Cold-Start L2 Benchmark Fails For Hyperlight
## Description

I have not been able to reproduce it locally.

### LINKED ISSUE #937: [utils] Cold-Start L2 Benchmark Fails For MicroVM
## Description

Cold-start benchmarks with the L2 VM are failing intermittently.

We should investigate and fix the issue.

### LINKED ISSUE #975: [utils] Warm-Start L2 Benchmark Fails for MicroVM
## Description

Warm-start benchmarks with the L2 VM are failing intermittently.

We should investigate and fix the issue.

### PR DESCRIPTION
**Pull request by csegarragonz**
In this PR I re-enable the L2 benchmarks for the Micro VM and Hyperlight. After the major re-factor, the race conditions that we were seeing should not no longer appear. I fix a few issues that were introduced precisely because we were not testing the L2 deployment at all.

Closes #975 
Closes #937
Closes #926

### CODE REVIEW

File: src/libs/syscomm/src/socket_unbound.rs
Comment (ppenna) [inline src/libs/syscomm/src/socket_unbound.rs:1]: Previous message was correct. We should tag the name of the function where the error message is located.

File: src/utils/nanvixd/src/args.rs [hunk 1]
```diff
@@ -140,6 +142,26 @@ impl Args {
...
+                warn!("{} and {}={} are incompatible options, overwriting {} to {}", Self::OPT_L2, Self::OPT_CONTROL_PLANE_SOCKET_TYPE, SocketType::UNIX_STR, Self::OPT_CONTROL_PLANE_SOCKET_TYPE, SocketType::TCP_STR);
+            }
+
+            if gateway_socket_type == Some(SocketType::UNIX_STR.to_string()) {
+                warn!("{} and {}={} are incompatible options, overwriting {} to {}", Self::OPT_L2, Self::OPT_GATEWAY_SOCKET_TYPE, SocketType::UNIX_STR, Self::OPT_GATEWAY_SOCKET_TYPE, SocketType::TCP_STR);
+            }
+
+            if system_vm_socket_type == Some(SocketType::UNIX_STR.to_string()) {
+                warn!("{} and {}={} are incompatible options, overwriting {} to {}", Self::OPT_L2, Self::OPT_SYSTEM_VM_SOCKET_TYPE, SocketType::UNIX_STR, Self::OPT_SYSTEM_VM_SOCKET_TYPE, SocketType::TCP_STR);
+            }
```
Comment (ppenna) [inline src/utils/nanvixd/src/args.rs:157]: Instead of testing for `UNIX` we should test for `TCP` and bail if not expected, logging will not work as this is not enabled at this point.

Comment (csegarragonz) [reply src/utils/nanvixd/src/args.rs:157]: This is not entirely correct. (The logging is).

To enable L2 deployments, we should only need to provide the `-l2` flag to nanvixd. However, for flexibility, we also support setting the individual `-control-plane-socket-type`. What I am trying to capture here is that setting both the `-l2` flag and _any_ `*-socket-type unix` is an invalid choice of arguments.

In addition, given that the default socket type is UNIX we need to explicitly set the socket types to TCP here.

Comment (ppenna) [reply src/utils/nanvixd/src/args.rs:157]: Yes, I agree. What I am suggesting is that we should not override any user informed parameters. Instead, we should check for them and fail if the combination is not valid.

Comment (csegarragonz) [reply src/utils/nanvixd/src/args.rs:157]: Agree. In this case the only invalid combination is `-l2` and `*-socket-type unix`. In which case we should `bail!`.

However, if `-l2` is set, we need to manually set the socket types to `tcp` because the default, when the argument is missing, is `unix`.
