### PR TITLE
[nanvix-sandbox] Fix acceptor blocking

### LINKED ISSUE #1996: [nanvix-sandbox] Control-plane handshake timeout on second nanvixd invocation in multi-process mode
## Description

The control-plane acceptor introduced in PR #1836 causes a 60-second timeout when a second `nanvixd` invocation attempts to spawn linuxd for the same tenant in multi-process mode. The first invocation succeeds; the second hangs waiting for the linuxd control-plane handshake and eventually fails:

```
Error: failed to get or create linuxd (tenant_id=runner, program=bzip2.elf,
  app_name=nanvixd-terminal,
  error=timed-out waiting for linuxd control-plane connection
  (tenant_id=runner, error=Elapsed(())))
```

## Reproduction

Observed in bzip2 CI (https://github.com/nanvix/bzip2/pull/82#issuecomment-4215403596):
- Configuration: `microvm-multi-process-256mb`
- Test 1 (sample1, `-1` compression) passes
- Test 2 (sample2, `-2` compression) fails with the timeout above
- All other CI configurations (standalone, single-process, hyperlight) pass

## Analysis

The timeout occurs in `SandboxCache::get_or_create_linuxd()` (`src/libs/nanvix-sandbox-cache/src/lib.rs`):

1. `register_linuxd("runner")` registers interest in the acceptor
2. `LinuxDaemon::spawn()` launches linuxd
3. `timeout(CONTROL_PLANE_ACCEPT_TIMEOUT, control_plane_stream_rx).await` waits 60s
4. Linuxd never sends its `ControlPlaneRegistrationMessage` -> timeout

Possible root causes:
- **Stale state from previous run**: The first run's linuxd connection or early-arrival buffer entry may not be fully cleaned up, interfering with the second registration for the same `tenant_id` (`"runner"`).
- **Acceptor routing mismatch**: If the second linuxd connects but its registration is routed to a stale entry rather than the new pending waiter.
- **Resource contention**: The shared `ControlPlaneAcceptor` listener may have a lingering accept that blocks the new connection.

## Files

- `src/libs/nanvix-sandbox-cache/src/lib.rs` (get_or_create_linuxd)
- `src/libs/nanvix-sandbox/src/control_plane_acceptor.rs` (acceptor state management)

## Severity

Medium -- causes intermittent CI failures in multi-process mode for downstream repos.

## References

- Introduced in PR #1836
- Related: #1994 (non-deterministic eviction), #1995 (missing tenant_id_len bound)

### PR DESCRIPTION
**Pull request by ppenna**
Spawn a per-connection tokio task in the accept loop instead of processing connections sequentially. A half-open stale connection blocked `read_registration()` for up to 60 s, preventing all other accepts and causing linuxd handshake timeouts on subsequent invocations.

Includes three regression tests that validate the fix.

Closes #1996

### CODE REVIEW

File: src/libs/nanvix-sandbox/src/control_plane_acceptor.rs [hunk 1]
```diff
@@ -297,58 +301,82 @@ impl ControlPlaneAcceptor {
...
-            // Notify awaiting peer, or store peer in early arrivals.
-            let mut state: MutexGuard<'_, ControlPlaneAcceptorState> = self.state.lock().await;
-            if let Some(waiter) = state.pending.remove(&peer) {
-                if waiter.send(stream).is_err() {
-                    warn!("run(): waiter dropped before control-plane delivery ({peer:?})");
-                }
-                continue;
-            }
+            // Spawn a task to read the registration and route the stream. This prevents a
+            // single slow connection from blocking the entire accept loop (#1996).
```
Comment (ppenna) [inline src/libs/nanvix-sandbox/src/control_plane_acceptor.rs]: Remove link to issue from comment. Comment should be:

```
// Spawn a task to read the registration and route the stream. This prevents a
// single slow connection from blocking the entire accept loop.
```
```
